apiVersion: apps/v1
kind: Deployment
metadata:
  name: datacollector
  argocd-image-updater.argoproj.io/image-list: asia-east1-docker.pkg.dev/homepage-436511/docker-repo/datacollector
  argocd-image-updater.argoproj.io/asia-east1-docker.pkg.dev/homepage-436511/docker-repo/datacollector.update-strategy: latest
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: datacollector
  template:
    metadata:
      labels:
        app: datacollector
    spec:
      containers:
      - image: asia-east1-docker.pkg.dev/homepage-436511/docker-repo/datacollector:latest
        name: datacollector
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: config-volume
          mountPath: /app/conf/config.yaml
          subPath: config.yaml
      imagePullSecrets:
        - name: gcp-artifact-registry
      volumes:
      - name: config-volume
        configMap:
          name: datacollector-config