apiVersion: v1
kind: Service
metadata:
  name: embeddingservice
spec:
  ports:
  - port: 8080
    name: http
    targetPort: 5000
  - port: 50051
    name: grpc
    targetPort: 50051
  selector:
    app: embeddingservice