apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: asia-east1-docker.pkg.dev/homepage-436511/docker-repo/ks-guestbook-demo:latest
        name: guestbook-ui
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: gcp-artifact-registry