apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: default
  namespace: argocd
spec:
  project: default
  source:
      repoURL: git@github.com:meowalien/discovery_system.git
      targetRevision: HEAD
      path: infrastructure/default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  revisionHistoryLimit: 0
#
#