redis:
  host: "localhost"
  port: 6379
  db: 0

postgres:
  url: "postgresql://postgres:postgres@localhost:5432/discovery_system"

http:
  host: "0.0.0.0"
  port:  8002
  log_level: "debug"

keycloak:
  url: "http://localhost:8082"
  realm: "discovery_system"
  client_id: "demo"
  audience: "account"
