redis:
  host: "redis"
  port: 6379
  db: 0

postgres:
  url: "postgresql://postgres:postgres@postgres.default:5432/discovery_system"

http:
  host: "0.0.0.0"
  port:  8002
  log_level: "debug"

keycloak:
  url: "http://keycloak:8080"
  realm: "discovery_system"
  client_id: "demo"
  audience: "account"

log_file_path: "/Users/jacky_li/logs/telegram_reader.log"

kafka:
  urls:
    - "kafka:9092"