# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import telegram_reader_pb2 as telegram__reader__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in telegram_reader_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TelegramReaderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateClient = channel.unary_unary(
                '/telegram.TelegramReaderService/CreateClient',
                request_serializer=telegram__reader__pb2.CreateClientRequest.SerializeToString,
                response_deserializer=telegram__reader__pb2.CreateClientResponse.FromString,
                _registered_method=True)
        self.LoadClient = channel.unary_unary(
                '/telegram.TelegramReaderService/LoadClient',
                request_serializer=telegram__reader__pb2.LoadClientRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.UnLoadClient = channel.unary_unary(
                '/telegram.TelegramReaderService/UnLoadClient',
                request_serializer=telegram__reader__pb2.UnLoadClientRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SignInClient = channel.unary_unary(
                '/telegram.TelegramReaderService/SignInClient',
                request_serializer=telegram__reader__pb2.SignInClientRequest.SerializeToString,
                response_deserializer=telegram__reader__pb2.SignInClientResponse.FromString,
                _registered_method=True)
        self.CompleteSignInClient = channel.unary_unary(
                '/telegram.TelegramReaderService/CompleteSignInClient',
                request_serializer=telegram__reader__pb2.CompleteSignInRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListClients = channel.unary_unary(
                '/telegram.TelegramReaderService/ListClients',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=telegram__reader__pb2.ListClientsResponse.FromString,
                _registered_method=True)
        self.GetDialogs = channel.unary_unary(
                '/telegram.TelegramReaderService/GetDialogs',
                request_serializer=telegram__reader__pb2.GetDialogsRequest.SerializeToString,
                response_deserializer=telegram__reader__pb2.GetDialogsResponse.FromString,
                _registered_method=True)
        self.StartReadMessage = channel.unary_unary(
                '/telegram.TelegramReaderService/StartReadMessage',
                request_serializer=telegram__reader__pb2.StartReadMessageRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class TelegramReaderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnLoadClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignInClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteSignInClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListClients(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDialogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartReadMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TelegramReaderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateClient': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateClient,
                    request_deserializer=telegram__reader__pb2.CreateClientRequest.FromString,
                    response_serializer=telegram__reader__pb2.CreateClientResponse.SerializeToString,
            ),
            'LoadClient': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadClient,
                    request_deserializer=telegram__reader__pb2.LoadClientRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UnLoadClient': grpc.unary_unary_rpc_method_handler(
                    servicer.UnLoadClient,
                    request_deserializer=telegram__reader__pb2.UnLoadClientRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SignInClient': grpc.unary_unary_rpc_method_handler(
                    servicer.SignInClient,
                    request_deserializer=telegram__reader__pb2.SignInClientRequest.FromString,
                    response_serializer=telegram__reader__pb2.SignInClientResponse.SerializeToString,
            ),
            'CompleteSignInClient': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteSignInClient,
                    request_deserializer=telegram__reader__pb2.CompleteSignInRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListClients': grpc.unary_unary_rpc_method_handler(
                    servicer.ListClients,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=telegram__reader__pb2.ListClientsResponse.SerializeToString,
            ),
            'GetDialogs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDialogs,
                    request_deserializer=telegram__reader__pb2.GetDialogsRequest.FromString,
                    response_serializer=telegram__reader__pb2.GetDialogsResponse.SerializeToString,
            ),
            'StartReadMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.StartReadMessage,
                    request_deserializer=telegram__reader__pb2.StartReadMessageRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'telegram.TelegramReaderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('telegram.TelegramReaderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TelegramReaderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/telegram.TelegramReaderService/CreateClient',
            telegram__reader__pb2.CreateClientRequest.SerializeToString,
            telegram__reader__pb2.CreateClientResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/telegram.TelegramReaderService/LoadClient',
            telegram__reader__pb2.LoadClientRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnLoadClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/telegram.TelegramReaderService/UnLoadClient',
            telegram__reader__pb2.UnLoadClientRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SignInClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/telegram.TelegramReaderService/SignInClient',
            telegram__reader__pb2.SignInClientRequest.SerializeToString,
            telegram__reader__pb2.SignInClientResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteSignInClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/telegram.TelegramReaderService/CompleteSignInClient',
            telegram__reader__pb2.CompleteSignInRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListClients(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/telegram.TelegramReaderService/ListClients',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            telegram__reader__pb2.ListClientsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDialogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/telegram.TelegramReaderService/GetDialogs',
            telegram__reader__pb2.GetDialogsRequest.SerializeToString,
            telegram__reader__pb2.GetDialogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartReadMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/telegram.TelegramReaderService/StartReadMessage',
            telegram__reader__pb2.StartReadMessageRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
