apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal
  labels:
    app: temporal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal
  template:
    metadata:
      labels:
        app: temporal
    spec:
      containers:
      - name: temporal
        image: temporalio/auto-setup:latest
        env:
        - name: DB
          value: "postgres12"
        - name: DB_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PWD
          value: "postgres"
        - name: POSTGRES_SEEDS
          value: "postgres"
        ports:
        - containerPort: 7233
          name: temporal
---
apiVersion: v1
kind: Service
metadata:
  name: temporal
spec:
  selector:
    app: temporal
  ports:
  - port: 7233
    targetPort: 7233
    name: temporal
---
# Temporal Admin Tools 部署（不對外暴露 Service）
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-admin-tools
  labels:
    app: temporal-admin-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-admin-tools
  template:
    metadata:
      labels:
        app: temporal-admin-tools
    spec:
      containers:
      - name: temporal-admin-tools
        image: temporalio/admin-tools:latest
        env:
        - name: TEMPORAL_ADDRESS
          value: "temporal:7233"
        - name: TEMPORAL_CLI_ADDRESS
          value: "temporal:7233"
        tty: true
        stdin: true
---
# Temporal UI 部署與 Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-ui
  labels:
    app: temporal-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-ui
  template:
    metadata:
      labels:
        app: temporal-ui
    spec:
      containers:
      - name: temporal-ui
        image: temporalio/ui:latest
        env:
        - name: TEMPORAL_ADDRESS
          value: "temporal:7233"
        - name: TEMPORAL_UI_PORT
          value: "7233"
        - name: TEMPORAL_CORS_ORIGINS
          value: "http://localhost:3000"
        ports:
        - containerPort: 8080
          name: temporal-ui
---
apiVersion: v1
kind: Service
metadata:
  name: temporal-ui
spec:
  selector:
    app: temporal-ui
  ports:
  - port: 8080
    targetPort: 8080
    name: temporal-ui