qdrant:
  host: "34.81.62.96"
  port: 6334
  api_key: "4tu892hl#%$^&pjo:gne;w*&("
embedding_service:
  host: "localhost"
  port: 50051

postgres:
  host: "postgres-headless.default"
  port: 5432
  user: "postgres"
  password: "postgres"
  db: "discovery_system"
  sslmode: "disable"
  timezone: "Asia/Taipei"

redis:
    host: "redis"
    port: 6379
    password: ""
    db: 0