// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: proto/telegram_reader.proto

package telegram_reader

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TelegramReaderService_CreateClient_FullMethodName         = "/telegram.TelegramReaderService/CreateClient"
	TelegramReaderService_LoadClient_FullMethodName           = "/telegram.TelegramReaderService/LoadClient"
	TelegramReaderService_UnLoadClient_FullMethodName         = "/telegram.TelegramReaderService/UnLoadClient"
	TelegramReaderService_SignInClient_FullMethodName         = "/telegram.TelegramReaderService/SignInClient"
	TelegramReaderService_CompleteSignInClient_FullMethodName = "/telegram.TelegramReaderService/CompleteSignInClient"
	TelegramReaderService_ListClients_FullMethodName          = "/telegram.TelegramReaderService/ListClients"
	TelegramReaderService_GetDialogs_FullMethodName           = "/telegram.TelegramReaderService/GetDialogs"
	TelegramReaderService_StartReadMessage_FullMethodName     = "/telegram.TelegramReaderService/StartReadMessage"
)

// TelegramReaderServiceClient is the client API for TelegramReaderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TelegramReaderServiceClient interface {
	CreateClient(ctx context.Context, in *CreateClientRequest, opts ...grpc.CallOption) (*CreateClientResponse, error)
	LoadClient(ctx context.Context, in *LoadClientRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UnLoadClient(ctx context.Context, in *UnLoadClientRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SignInClient(ctx context.Context, in *SignInClientRequest, opts ...grpc.CallOption) (*SignInClientResponse, error)
	CompleteSignInClient(ctx context.Context, in *CompleteSignInRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListClients(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListClientsResponse, error)
	GetDialogs(ctx context.Context, in *GetDialogsRequest, opts ...grpc.CallOption) (*GetDialogsResponse, error)
	StartReadMessage(ctx context.Context, in *StartReadMessageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type telegramReaderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTelegramReaderServiceClient(cc grpc.ClientConnInterface) TelegramReaderServiceClient {
	return &telegramReaderServiceClient{cc}
}

func (c *telegramReaderServiceClient) CreateClient(ctx context.Context, in *CreateClientRequest, opts ...grpc.CallOption) (*CreateClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateClientResponse)
	err := c.cc.Invoke(ctx, TelegramReaderService_CreateClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telegramReaderServiceClient) LoadClient(ctx context.Context, in *LoadClientRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TelegramReaderService_LoadClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telegramReaderServiceClient) UnLoadClient(ctx context.Context, in *UnLoadClientRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TelegramReaderService_UnLoadClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telegramReaderServiceClient) SignInClient(ctx context.Context, in *SignInClientRequest, opts ...grpc.CallOption) (*SignInClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignInClientResponse)
	err := c.cc.Invoke(ctx, TelegramReaderService_SignInClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telegramReaderServiceClient) CompleteSignInClient(ctx context.Context, in *CompleteSignInRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TelegramReaderService_CompleteSignInClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telegramReaderServiceClient) ListClients(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListClientsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListClientsResponse)
	err := c.cc.Invoke(ctx, TelegramReaderService_ListClients_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telegramReaderServiceClient) GetDialogs(ctx context.Context, in *GetDialogsRequest, opts ...grpc.CallOption) (*GetDialogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDialogsResponse)
	err := c.cc.Invoke(ctx, TelegramReaderService_GetDialogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telegramReaderServiceClient) StartReadMessage(ctx context.Context, in *StartReadMessageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TelegramReaderService_StartReadMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TelegramReaderServiceServer is the server API for TelegramReaderService service.
// All implementations must embed UnimplementedTelegramReaderServiceServer
// for forward compatibility.
type TelegramReaderServiceServer interface {
	CreateClient(context.Context, *CreateClientRequest) (*CreateClientResponse, error)
	LoadClient(context.Context, *LoadClientRequest) (*emptypb.Empty, error)
	UnLoadClient(context.Context, *UnLoadClientRequest) (*emptypb.Empty, error)
	SignInClient(context.Context, *SignInClientRequest) (*SignInClientResponse, error)
	CompleteSignInClient(context.Context, *CompleteSignInRequest) (*emptypb.Empty, error)
	ListClients(context.Context, *emptypb.Empty) (*ListClientsResponse, error)
	GetDialogs(context.Context, *GetDialogsRequest) (*GetDialogsResponse, error)
	StartReadMessage(context.Context, *StartReadMessageRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedTelegramReaderServiceServer()
}

// UnimplementedTelegramReaderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTelegramReaderServiceServer struct{}

func (UnimplementedTelegramReaderServiceServer) CreateClient(context.Context, *CreateClientRequest) (*CreateClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateClient not implemented")
}
func (UnimplementedTelegramReaderServiceServer) LoadClient(context.Context, *LoadClientRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadClient not implemented")
}
func (UnimplementedTelegramReaderServiceServer) UnLoadClient(context.Context, *UnLoadClientRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnLoadClient not implemented")
}
func (UnimplementedTelegramReaderServiceServer) SignInClient(context.Context, *SignInClientRequest) (*SignInClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignInClient not implemented")
}
func (UnimplementedTelegramReaderServiceServer) CompleteSignInClient(context.Context, *CompleteSignInRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteSignInClient not implemented")
}
func (UnimplementedTelegramReaderServiceServer) ListClients(context.Context, *emptypb.Empty) (*ListClientsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListClients not implemented")
}
func (UnimplementedTelegramReaderServiceServer) GetDialogs(context.Context, *GetDialogsRequest) (*GetDialogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDialogs not implemented")
}
func (UnimplementedTelegramReaderServiceServer) StartReadMessage(context.Context, *StartReadMessageRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartReadMessage not implemented")
}
func (UnimplementedTelegramReaderServiceServer) mustEmbedUnimplementedTelegramReaderServiceServer() {}
func (UnimplementedTelegramReaderServiceServer) testEmbeddedByValue()                               {}

// UnsafeTelegramReaderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelegramReaderServiceServer will
// result in compilation errors.
type UnsafeTelegramReaderServiceServer interface {
	mustEmbedUnimplementedTelegramReaderServiceServer()
}

func RegisterTelegramReaderServiceServer(s grpc.ServiceRegistrar, srv TelegramReaderServiceServer) {
	// If the following call pancis, it indicates UnimplementedTelegramReaderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TelegramReaderService_ServiceDesc, srv)
}

func _TelegramReaderService_CreateClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramReaderServiceServer).CreateClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelegramReaderService_CreateClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramReaderServiceServer).CreateClient(ctx, req.(*CreateClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegramReaderService_LoadClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramReaderServiceServer).LoadClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelegramReaderService_LoadClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramReaderServiceServer).LoadClient(ctx, req.(*LoadClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegramReaderService_UnLoadClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnLoadClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramReaderServiceServer).UnLoadClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelegramReaderService_UnLoadClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramReaderServiceServer).UnLoadClient(ctx, req.(*UnLoadClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegramReaderService_SignInClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramReaderServiceServer).SignInClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelegramReaderService_SignInClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramReaderServiceServer).SignInClient(ctx, req.(*SignInClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegramReaderService_CompleteSignInClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteSignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramReaderServiceServer).CompleteSignInClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelegramReaderService_CompleteSignInClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramReaderServiceServer).CompleteSignInClient(ctx, req.(*CompleteSignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegramReaderService_ListClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramReaderServiceServer).ListClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelegramReaderService_ListClients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramReaderServiceServer).ListClients(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegramReaderService_GetDialogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDialogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramReaderServiceServer).GetDialogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelegramReaderService_GetDialogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramReaderServiceServer).GetDialogs(ctx, req.(*GetDialogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegramReaderService_StartReadMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartReadMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramReaderServiceServer).StartReadMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelegramReaderService_StartReadMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramReaderServiceServer).StartReadMessage(ctx, req.(*StartReadMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TelegramReaderService_ServiceDesc is the grpc.ServiceDesc for TelegramReaderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TelegramReaderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "telegram.TelegramReaderService",
	HandlerType: (*TelegramReaderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateClient",
			Handler:    _TelegramReaderService_CreateClient_Handler,
		},
		{
			MethodName: "LoadClient",
			Handler:    _TelegramReaderService_LoadClient_Handler,
		},
		{
			MethodName: "UnLoadClient",
			Handler:    _TelegramReaderService_UnLoadClient_Handler,
		},
		{
			MethodName: "SignInClient",
			Handler:    _TelegramReaderService_SignInClient_Handler,
		},
		{
			MethodName: "CompleteSignInClient",
			Handler:    _TelegramReaderService_CompleteSignInClient_Handler,
		},
		{
			MethodName: "ListClients",
			Handler:    _TelegramReaderService_ListClients_Handler,
		},
		{
			MethodName: "GetDialogs",
			Handler:    _TelegramReaderService_GetDialogs_Handler,
		},
		{
			MethodName: "StartReadMessage",
			Handler:    _TelegramReaderService_StartReadMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/telegram_reader.proto",
}
