name: Build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'python/embedding_service/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure all tags are fetched

      - name: Get Git Tag or Short SHA
        id: get_version
        run: |
          TAG=$(git describe --tags --exact-match 2>/dev/null || echo "")
          if [ -z "$TAG" ]; then
            TAG=$(git rev-parse --short=8 HEAD)  # Get first 8 characters of SHA
          fi
          echo "VERSION=$TAG" >> $GITHUB_ENV
          echo "Computed VERSION: $TAG"

      - name: Authenticate with Google Artifact Registry
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure Docker to use Google Artifact Registry
        run: |
          gcloud auth configure-docker asia-east1-docker.pkg.dev

      - name: Build and Push Multi-Platform Image
        uses: docker/build-push-action@v4
        with:
          context: python/embedding_service
          file: python/embedding_service/Dockerfile
          push: true
#          linux/arm64
          platforms: linux/amd64
          tags: |
            asia-east1-docker.pkg.dev/homepage-436511/docker-repo/embeddingservice:${{ env.VERSION }}
            asia-east1-docker.pkg.dev/homepage-436511/docker-repo/embeddingservice:latest
          build-args: |
            VERSION=${{ env.VERSION }}