name: Folder Changes CI

on:
  push:
    # 只監聽 main 分支(可自行調整)
    branches: [ "main" ]
    # 只有在這些路徑發生變動時，才會觸發工作流程
    paths:
      - 'infrastructure/**'


jobs:
  # A action job：當 infrastructure 資料夾有變動時才執行
  infrastructure-edit-action:
    runs-on: ubuntu-latest
    steps:
      - name: Run A Action
        run: echo "Run A Action because infrastructure folder changed."
